# Generated by Django 5.0.10 on 2024-12-31 00:01

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContestantImage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="The unique identifier of an object.",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        help_text="Timestamp when the record was created. The date and time\n            are displayed in the Timezone from where request is made.\n            e.g. 2019-14-29T00:15:09Z for April 29, 2019 0:15:09 UTC",
                        verbose_name="Created",
                    ),
                ),
                (
                    "modified_date",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the record was modified. The date and\n            time are displayed in the Timezone from where request\n            is made. e.g. 2019-14-29T00:15:09Z for April 29, 2019 0:15:09 UTC\n            ",
                        null=True,
                        verbose_name="Updated",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        help_text="this hold the contestant image",
                        null=True,
                        upload_to="images/",
                        verbose_name="Contestant Images",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contestant Image",
                "verbose_name_plural": "Contestant Image",
                "ordering": ["-created_date"],
            },
        ),
        migrations.CreateModel(
            name="ContestantStage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="The unique identifier of an object.",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        help_text="Timestamp when the record was created. The date and time\n            are displayed in the Timezone from where request is made.\n            e.g. 2019-14-29T00:15:09Z for April 29, 2019 0:15:09 UTC",
                        verbose_name="Created",
                    ),
                ),
                (
                    "modified_date",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the record was modified. The date and\n            time are displayed in the Timezone from where request\n            is made. e.g. 2019-14-29T00:15:09Z for April 29, 2019 0:15:09 UTC\n            ",
                        null=True,
                        verbose_name="Updated",
                    ),
                ),
                (
                    "stage",
                    models.CharField(
                        blank=True,
                        help_text="this hold the Stage which will is active",
                        max_length=100,
                        null=True,
                        verbose_name="Stage",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contestant Stage",
                "verbose_name_plural": "Contestant Stage",
                "ordering": ["-created_date"],
            },
        ),
        migrations.CreateModel(
            name="ContestantVideo",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="The unique identifier of an object.",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        help_text="Timestamp when the record was created. The date and time\n            are displayed in the Timezone from where request is made.\n            e.g. 2019-14-29T00:15:09Z for April 29, 2019 0:15:09 UTC",
                        verbose_name="Created",
                    ),
                ),
                (
                    "modified_date",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the record was modified. The date and\n            time are displayed in the Timezone from where request\n            is made. e.g. 2019-14-29T00:15:09Z for April 29, 2019 0:15:09 UTC\n            ",
                        null=True,
                        verbose_name="Updated",
                    ),
                ),
                (
                    "video_file",
                    models.FileField(upload_to="videos/", verbose_name="Video File"),
                ),
            ],
            options={
                "verbose_name": "Contestant Video",
                "verbose_name_plural": "Contestant Video",
                "ordering": ["-created_date"],
            },
        ),
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                help_text="The unique identifier of the agent.",
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.CreateModel(
            name="Contestant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="The unique identifier of an object.",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        help_text="Timestamp when the record was created. The date and time\n            are displayed in the Timezone from where request is made.\n            e.g. 2019-14-29T00:15:09Z for April 29, 2019 0:15:09 UTC",
                        verbose_name="Created",
                    ),
                ),
                (
                    "modified_date",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the record was modified. The date and\n            time are displayed in the Timezone from where request\n            is made. e.g. 2019-14-29T00:15:09Z for April 29, 2019 0:15:09 UTC\n            ",
                        null=True,
                        verbose_name="Updated",
                    ),
                ),
                (
                    "contestant_id",
                    models.CharField(
                        blank=True,
                        help_text="this hold the contestant id which will be automatically generated",
                        max_length=10,
                        null=True,
                        verbose_name="Contestant ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Name of Contestant"
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        help_text="this hold the First Name of the contestant",
                        max_length=100,
                        null=True,
                        verbose_name="First Name",
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        help_text="this hold the last name of the contestant ",
                        max_length=100,
                        null=True,
                        verbose_name="Last Name",
                    ),
                ),
                (
                    "stage_name",
                    models.CharField(
                        help_text="this hold the stage name of the contestant ",
                        max_length=100,
                        null=True,
                        verbose_name="Stage Name",
                    ),
                ),
                (
                    "contestant_inspiration",
                    models.CharField(
                        help_text="this hold the contestant inspiration toward the competition",
                        max_length=50,
                        null=True,
                        verbose_name="Contestant Inspiration",
                    ),
                ),
                (
                    "number_of_vote",
                    models.IntegerField(
                        blank=True,
                        default=0,
                        help_text="this displays the contestant vote count",
                        null=True,
                        verbose_name="Contestant Votes",
                    ),
                ),
                ("contestant_videos", models.JSONField(default=list)),
                (
                    "contestant_images",
                    models.ManyToManyField(to="users.contestantimage"),
                ),
            ],
            options={
                "verbose_name": "Contestant Profile",
                "verbose_name_plural": "Contestant Profile",
                "ordering": ["-created_date"],
            },
        ),
        migrations.CreateModel(
            name="Transactions",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="The unique identifier of an object.",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        help_text="Timestamp when the record was created. The date and time\n            are displayed in the Timezone from where request is made.\n            e.g. 2019-14-29T00:15:09Z for April 29, 2019 0:15:09 UTC",
                        verbose_name="Created",
                    ),
                ),
                (
                    "modified_date",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the record was modified. The date and\n            time are displayed in the Timezone from where request\n            is made. e.g. 2019-14-29T00:15:09Z for April 29, 2019 0:15:09 UTC\n            ",
                        null=True,
                        verbose_name="Updated",
                    ),
                ),
                (
                    "amount_paid",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="this hold the amount paid",
                        max_digits=20,
                        null=True,
                        verbose_name="Amount Paid",
                    ),
                ),
                (
                    "payment_ref",
                    models.CharField(
                        help_text="this hold the Transaction Ref for the current transaction ",
                        max_length=100,
                        null=True,
                        verbose_name="Transaction Ref",
                    ),
                ),
                (
                    "voter_name",
                    models.CharField(
                        help_text="this hold the Voter name of the contestant ",
                        max_length=100,
                        null=True,
                        verbose_name="Voter Name",
                    ),
                ),
                (
                    "voter_email",
                    models.EmailField(
                        help_text="this hold the Voter email of the contestant ",
                        max_length=254,
                        null=True,
                        verbose_name="Voter Email",
                    ),
                ),
                (
                    "voter_phone_number",
                    models.BigIntegerField(
                        blank=True,
                        help_text="this displays the voter phone number",
                        null=True,
                        verbose_name="Voter phone Number",
                    ),
                ),
                (
                    "settled",
                    models.BooleanField(
                        default=False, null=True, verbose_name="Payment Settled"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        help_text="this hold the Voter name of the contestant ",
                        max_length=100,
                        null=True,
                        verbose_name="Status",
                    ),
                ),
                (
                    "contestant",
                    models.ForeignKey(
                        help_text="this hold the contestant account details",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="users.contestant",
                        verbose_name="Contestant Account",
                    ),
                ),
            ],
            options={
                "verbose_name": "Transactions",
                "verbose_name_plural": "Transactions",
                "ordering": ["-created_date"],
            },
        ),
    ]
