# Generated by Django 5.0.10 on 2025-01-07 07:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_contestantimage_contestantstage_contestantvideo_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contestant",
            name="contestant_images",
            field=models.ManyToManyField(
                related_name="contestants", to="users.contestantimage"
            ),
        ),
        migrations.AlterField(
            model_name="contestant",
            name="contestant_videos",
            field=models.JSONField(
                default="['https://www.youtube.com/watch?v=6v2L2UGZJAM']"
            ),
        ),
        migrations.AlterField(
            model_name="contestantimage",
            name="image",
            field=models.ImageField(
                help_text="this hold the contestant image",
                null=True,
                upload_to="contestant_images/",
                verbose_name="Contestant Images",
            ),
        ),
    ]
